-- others
vim.api.nvim_create_user_command('G', function() vim.cmd('Git') vim.cmd('only') end, {})

-- Helpers
function cancel_tmux_cmd() vim.cmd("silent! !tmux send-keys -X -t " .. vim.g.my_tmux_target .. " 'cancel'") end
function tmux_cmd(command)
  vim.cmd("silent! !tmux send-keys -X -t " .. vim.g.my_tmux_target .. " 'cancel'")
  vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " '" .. command .. "' Enter")
end
vim.api.nvim_create_user_command('OpenFiles', function()
  vim.fn.system('git rev-parse --is-inside-work-tree')
  if vim.v.shell_error == 0 then
    vim.cmd('GFiles')
  else
    vim.cmd('Files')
  end
end, {})

-- Key mappings
function map(mode, lhs, rhs, opts) vim.keymap.set(mode, lhs, rhs, opts) end
function nmap(lhs, rhs, opts) return map('n', lhs, rhs, opts) end
function imap(lhs, rhs, opts) return map('i', lhs, rhs, opts) end
function vmap(lhs, rhs, opts) return map('v', lhs, rhs, opts) end
function cmap(lhs, rhs, opts) return map('c', lhs, rhs, opts) end

cmap('<C-n>', '<down>', { noremap = true })
cmap('<C-p>', '<Up>', { noremap = true })
imap('jk', '<Esc>', { noremap = true })
vmap('<C-r>', '"hy:%s/<C-r>h//g<left><left>', { noremap = true })

nmap('<Space>', '<Nop>', { noremap = true, silent = true })
nmap('<C-f>', '<cmd>Ag<cr>', { noremap = true, desc = "FindFiles" })
nmap('<slient><C-h>', '<C-U>TmuxNavigateLeft<cr>', { noremap = true })
nmap('<slient><C-j>', '<C-U>TmuxNavigateDown<cr>', { noremap = true })
nmap('<slient><C-k>', '<C-U>TmuxNavigateUp<cr>', { noremap = true })
nmap('<slient><C-l>', '<C-U>TmuxNavigateRight<cr>', { noremap = true })
nmap('<C-p>', '<cmd>OpenFiles<cr>', { noremap = true, desc = "Telescope" })
nmap('<C-t>', '<cmd>Neotree toggle<cr>', { noremap = true, desc = "Tree toggle" })
nmap('<leader>+', ':12winc +<CR>', { noremap = true })
nmap('<leader>-', ':12winc -<CR>', { noremap = true })
nmap('<leader>=', ':12winc ><CR>', { noremap = true })
nmap('<leader>[', "<cmd>Gitsigns prev_hunk<cr>", { desc = "Prev hunk" })
nmap('<leader>[', ':Gitsigns prev_hunk<CR>', { noremap = true, silent = true })
nmap('<leader>]', "<cmd>Gitsigns next_hunk<cr>", { desc = "Next hunk" })
nmap('<leader>]', ':Gitsigns next_hunk<CR>', { noremap = true, silent = true })
nmap('<leader>_', ':12winc <<CR>', { noremap = true })
nmap('<leader>a', "<cmd>lua vim.lsp.buf.code_action()<cr>", { desc = "Code Action" })
nmap('<leader>a', "<cmd>lua vim.lsp.buf.code_action()<cr>", { noremap = true, desc = "Code Action" })
nmap('<leader>ba', "<cmd>Buffers<cr>", { noremap = true, desc = "Buffers" })
nmap('<leader>gb', ':Gitsigns blame_line<CR>', { noremap = true, silent = true })
nmap('<leader>gp', ':Gitsigns preview_hunk<CR>', { noremap = true, silent = true })
nmap('<leader>gr', ':Gitsigns reset_hunk<CR>', { noremap = true, silent = true })
nmap('<leader>gs', ':Gitsigns stage_hunk<CR>', { noremap = true, silent = true })
nmap('<leader>gu', ':Gitsigns undo_stage_hunk<CR>', { noremap = true, silent = true })
nmap('<leader>j', function() require("astrocore.buffer").nav(-vim.v.count1) end, { noremap = true, desc = "Next buffer" })
nmap('<leader>k', function() require("astrocore.buffer").nav(vim.v.count1) end, { noremap = true, desc = "Next buffer" })
nmap('<leader>n', "<cmd>Neotree reveal<cr>", { noremap = true, desc = "Tree reveal" })
nmap('<leader>o', ':on<CR>', { noremap = true, desc = "Buffer only", silent = true })
nmap('<leader>rb', function() vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " 'break '" ..  vim.fn.expand('%:p') .. ":" .. vim.fn.line('.') .. " Enter") end, { noremap = true })
nmap('<leader>rc', ':!rubocop -a %<CR>', { noremap = true })
nmap('<leader>rf', function() tmux_cmd('rspec ' .. vim.fn.expand('%:p') .. ' -f p') end, { noremap = true })
nmap('<leader>rj', function() tmux_cmd('yarn vitest ' .. vim.fn.expand('%:p')) end, { noremap = true })
nmap('<leader>rk', function() cancel_tmux_cmd(); vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " 'rspec ' Up Enter") end, { noremap = true })
nmap('<leader>rl', function() tmux_cmd('rspec ' .. vim.fn.expand('%:p') .. ':' .. vim.fn.line('.') .. ' -f d') end, { noremap = true })
nmap('<leader>rp', ':!yarn eslint --fix --ext .vue,.ts,.js %<CR>', { noremap = true })
nmap('<leader>rq', function() vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " 'exit-program' Enter") end, { noremap = true })
nmap('<leader>rv', "<cmd>AstroReload<cr>", { desc = "Reload astro" })
nmap('<leader>ww', "<cmd>Bdelete<cr>", { noremap = true, desc = "Close buffer" })
nmap('[g', function() vim.diagnostic.goto_prev() end, { noremap = true, desc = "Go to prev diagnostic" })
nmap(']g', function() vim.diagnostic.goto_next() end, { noremap = true, desc = "Go to next diagnostic" })
nmap('n', function() return (vim.v.searchforward == 1 and 'n' or 'N') .. 'zz' end, { expr = true, noremap = true })
nmap('N', function() return (vim.v.searchforward == 1 and 'N' or 'n') .. 'zz' end, { expr = true, noremap = true })
nmap('zt', 'ztkj', { noremap = true })

--
-- fzf pending
-- nmap('<leader>[', function() vim.diagnostic.goto_prev() end, { noremap = true })
-- nmap('<leader>]', function() vim.diagnostic.goto_next() end, { noremap = true })
-- nmap('<leader>qd', ':CocDiagnostics<cr>', { noremap = true })
-- nmap('<leader>qf', '<Plug>(coc-fix-current)', { noremap = true })
-- nmap('<leader>rn', '<Plug>(coc-rename)', { noremap = true })
-- nmap('<slient><leader>a', '<Plug>(coc-codeaction-cursor)', { noremap = true })
-- nmap('<slient><leader>a', '<Plug>(coc-codeaction-selected)', { noremap = true })
-- nmap('<slient>gD', function() vim.lsp.buf.implementation() end, { noremap = true })
-- nmap('<slient>gf', function() vim.lsp.buf.definitions() end, { noremap = true })
-- nmap('<slient>gr', '<Plug>(coc-references)', { noremap = true })
-- print('Custom keymaps loaded')
-- cmap('<C-n>', '<down>', { noremap = true })
-- cmap('<C-p>', '<Up>', { noremap = true })
-- imap('jk', '<Esc>', { noremap = true })
-- nmap('<C-n>', ':NERDTree<CR>', { noremap = true })
-- nmap('<C-t>', ':NERDTreeToggle<CR>', { noremap = true })
-- nmap('<Space>', '<Nop>', { noremap = true, silent = true })
-- nmap('<leader>+', ':12winc +<CR>', { noremap = true })
-- nmap('<leader>-', ':12winc -<CR>', { noremap = true })
-- nmap('<leader>=', ':12winc ><CR>', { noremap = true })
-- nmap('<leader>_', ':12winc <<CR>', { noremap = true })
-- nmap('<leader>j', ':bp<CR>', { noremap = true })
-- nmap('<leader>k', '', { noremap = true })
-- nmap('<leader>n', ':NERDTreeFind<CR>', { noremap = true })
-- nmap('<leader>o', ':on<CR>', { noremap = true })
-- nmap('<leader>rb', function() vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " 'break '" ..  vim.fn.expand('%:p') .. ":" .. vim.fn.line('.') .. " Enter") end, { noremap = true })
-- nmap('<leader>rc', ':!rubocop -a %<CR>', { noremap = true })
-- nmap('<leader>rf', function() tmux_cmd('rspec ' .. vim.fn.expand('%:p') .. ' -f p') end, { noremap = true })
-- nmap('<leader>rj', function() tmux_cmd('yarn vitest ' .. vim.fn.expand('%:p')) end, { noremap = true })
-- nmap('<leader>rk', function() cancel_tmux_cmd(); vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " 'rspec ' Up Enter") end, { noremap = true })
-- nmap('<leader>rl', function() tmux_cmd('rspec ' .. vim.fn.expand('%:p') .. ':' .. vim.fn.line('.') .. ' -f d') end, { noremap = true })
-- nmap('<leader>rp', ':!yarn eslint --fix --ext .vue,.ts,.js %<CR>', { noremap = true })
-- nmap('<leader>rq', function() vim.cmd("silent! !tmux send -t " .. vim.g.my_tmux_target .. " 'exit-program' Enter") end, { noremap = true })
-- nmap('<leader>rv', ':source ~/.config/nvim/init.lua<CR>', { noremap = true })
-- nmap('<silent><leader>[', ':Gitsigns prev_hunk<CR>', { noremap = true })
-- nmap('<silent><leader>]', ':Gitsigns next_hunk<CR>', { noremap = true })
-- nmap('<silent><leader>gb', ':Gitsigns blame_line<CR>', { noremap = true })
-- nmap('<silent><leader>gp', ':Gitsigns preview_hunk<CR>', { noremap = true })
-- nmap('<silent><leader>gr', ':Gitsigns reset_hunk<CR>', { noremap = true })
-- nmap('<silent><leader>gs', ':Gitsigns stage_hunk<CR>', { noremap = true })
-- nmap('<silent><leader>gu', ':Gitsigns undo_stage_hunk<CR>', { noremap = true })
-- nmap('<slient><C-h>', '<C-U>TmuxNavigateLeft<cr>', { noremap = true })
-- nmap('<slient><C-j>', '<C-U>TmuxNavigateDown<cr>', { noremap = true })
-- nmap('<slient><C-k>', '<C-U>TmuxNavigateUp<cr>', { noremap = true })
-- nmap('<slient><C-l>', '<C-U>TmuxNavigateRight<cr>', { noremap = true })
-- nmap('[g', '<cmd>lua vim.diagnostic.goto_prev()<cr>', { noremap = true, desc = "Go to prev diagnostic" })
-- nmap(']g', '<cmd>lua vim.diagnostic.goto_next()<cr>', { noremap = true, desc = "Go to next diagnostic" })
-- nmap('zt', 'ztkj', { noremap = true })
